services:
  web:
    build: .
    container_name: web
    command: gunicorn --access-logfile - --error-logfile - --timeout 3600 auth.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/static/
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
    driver: local
